global using Microsoft.AspNetCore.DataProtection;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
global using MinimalHelpers.Routing;
global using SampleAuthJWT.BusinessLayer.Extensions;
global using SampleAuthJWT.DataAccessLayer;
global using SampleAuthJWT.DataAccessLayer.Entities;
global using SimpleAuthentication;
global using TinyHelpers.AspNetCore.Extensions;
